@startuml Открытие депозита - Context Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Онлайн заявка на кредит (Context)
AddRelTag("asyncLine", $lineStyle=DashedLine())

' Чего только не делал, чтобы клиент "всплыл" вверх - не хочет -___-

Person(customer, "клиент", "")


Boundary(credit_b, "Кредитное направление", "Логическая группа"){
    System(credit_score, "Кредитный скоринг", "", "", "")
    System(conveer, "Кредитный конвеер", "", "", "")
    System_Ext(buro, "Бюро кредитных историй")
}

Boundary(bank, "Система интернет-банка", ""){
    Container(site, "Сайт", "JS/React.js")
    Container(gateway, "Gateway", "C#/Ocelot")
    Container(offers_service, "Сервис предложений", "C#/.NET", "Получение информации о продуктах и ставках")
    Container(offers_service_db, "База данных сервиса предложений", "MS SQL")
    Container(offers_service_cache, "Кэш Сервиса предложений", "Redis")
    Container(customer_center, "Центр обработки заявок", "C#/.NET, REST", "Конвеер по обработке продуктовых заявок от пользователей")
    Container(customer_center_db, "База данных центра обработки заявок ","MS SQL")
    Container(internet_bank, "Интернет банк", "C#/.NET", "(текущий монолит)")
    Container(internal_gateway, "Внутренний API Gateway", "C#/Ocelot", "", "")
}

System(abc, "АБС", "", "", "delphi")

System(sms_gateway, "Смс шлюз")
System_Ext(sms_provider, "Телеком провайдер")

Rel(customer, site, "Просмотр ставок, оформление кредита")

Rel(site, gateway, "", "http/https")

Rel(offers_service, offers_service_db, "", "read/write")
Rel(customer_center, customer_center_db, "", "read/write")
Rel(customer_center, offers_service_cache, "", "read/write")

Rel(gateway, internet_bank, "", "https")
Rel(gateway, offers_service, "Получить предложения и ставки", "http/https")
Rel(gateway, customer_center, "", "http/https")

Rel_R(abc, sms_gateway, "")

Rel(abc, conveer, "", $tags="asyncLine" )
Rel(conveer, abc, "обработка кредитной заявки сотрудником бэк-офиса", )

Rel(sms_gateway, sms_provider, "Отправка смс", "REST?")
Rel(sms_provider, customer, "Доставка смс", $tags="asyncLine")

Rel(credit_score, buro, "")
Rel(credit_score, abc, "")

Rel(internet_bank, internal_gateway, "", "REST")
Rel(offers_service, internal_gateway, "", "REST")
Rel(customer_center, internal_gateway, "", "REST")
Rel(internal_gateway, sms_gateway, "Отправка кода-подтверждения", "REST")
Rel(internal_gateway, conveer, "Отправление кредитной заявки", "REST")
Rel(internal_gateway, credit_score, "Получение предодобреддных кредитных предложений", "REST")

Rel(abc, customer_center, "Обновление статуса заявки", "REST")

Lay_U(bank, customer)
Lay_U(site, customer)
Lay_U(abc, customer)

@enduml